### ISSUE TITLE
Version 102 never finishes loading

### ISSUE THREAD

**Issue by ianturk** [six7/figma-tokens#811]
**Describe the bug**
Figma Tokens never finishes loading. Tried closing and reopening the plug-in and quitting and restarting Figma. Still won't finish loading.

**To Reproduce**
1. Open Figma Tokens

**Expected behavior**
Figma Tokens loads

**Screenshots or Screencasts**
<img width="492" alt="Screen Shot 2022-06-03 at 18 34 27" src="https://user-images.githubusercontent.com/3350351/171972078-1da178af-6f62-4079-a135-6af2c12ae8fc.png">

**Comment by ianturk** [comment]
Opens fine in a blank file. The issue happens in an existing file with tokens.

**Comment by six7** [comment]
Fixed in 103, thank you for the details ❤️

**Comment by thomasboulongne** [comment]
I'm still having this issue when I open a file with tokens synced with Github on a new computer (version 104). Would you want me to open a new issue?

**Comment by six7** [comment]
> I'm still having this issue when I open a file with tokens synced with Github on a new computer (version 104). Would you want me to open a new issue?

Yes please 👍 if possible provide as many details as you can, also inviting me to your figma file / the repo (or a clone of it) would help immensely 🙏

**Comment by ianturk** [comment]
At least one of our team members is still experiencing this in the same file that I sent. Granted, I did setup ADO support on my end.

**Comment by six7** [comment]
> At least one of our team members is still experiencing this in the same file that I sent. Granted, I did setup ADO support on my end.

We identified an issue and published a fix several hours ago. Please let me know if the issue still occurs 🙏

**Comment by thomasboulongne** [comment]
Seems fixed here! Thank you!
